# Generated by Django 2.0.13 on 2019-06-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('usuario', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=60)),
            ],
        ),
    ]
