# Generated by Django 2.0.13 on 2019-06-22 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Users',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='usuario',
            new_name='username',
        ),
    ]
